./bwr 0
./bwr 1
./bwr 2
./bwr 3
./bwr 4
./bwr 5
echo      1	 | ./gen_input | ./bwr -
echo      2	 | ./gen_input | ./bwr -
echo      3	 | ./gen_input | ./bwr -
echo      4	 | ./gen_input | ./bwr -
echo      5	 | ./gen_input | ./bwr -
echo      6	 | ./gen_input | ./bwr -
echo      7	 | ./gen_input | ./bwr -
echo      8	 | ./gen_input | ./bwr -
echo      9	 | ./gen_input | ./bwr -
echo     10	 | ./gen_input | ./bwr -
echo     11	 | ./gen_input | ./bwr -
echo     12	 | ./gen_input | ./bwr -
echo     13	 | ./gen_input | ./bwr -
echo     14	 | ./gen_input | ./bwr -
echo     15	 | ./gen_input | ./bwr -
echo     16	 | ./gen_input | ./bwr -
echo     17	 | ./gen_input | ./bwr -
echo     18	 | ./gen_input | ./bwr -
echo     19	 | ./gen_input | ./bwr -
echo     20	 | ./gen_input | ./bwr -
echo     21	 | ./gen_input | ./bwr -
echo     22	 | ./gen_input | ./bwr -
echo     23	 | ./gen_input | ./bwr -
echo     24	 | ./gen_input | ./bwr -
echo     25	 | ./gen_input | ./bwr -
echo     26	 | ./gen_input | ./bwr -
echo     27	 | ./gen_input | ./bwr -
echo     28	 | ./gen_input | ./bwr -
echo     29	 | ./gen_input | ./bwr -
echo     30	 | ./gen_input | ./bwr -
echo     31	 | ./gen_input | ./bwr -
echo     32	 | ./gen_input | ./bwr -
echo     33	 | ./gen_input | ./bwr -
echo     34	 | ./gen_input | ./bwr -
echo     35	 | ./gen_input | ./bwr -
echo     36	 | ./gen_input | ./bwr -
echo     37	 | ./gen_input | ./bwr -
echo     38	 | ./gen_input | ./bwr -
echo     39	 | ./gen_input | ./bwr -
echo     40	 | ./gen_input | ./bwr -
echo     41	 | ./gen_input | ./bwr -
echo     42	 | ./gen_input | ./bwr -
echo     43	 | ./gen_input | ./bwr -
echo     44	 | ./gen_input | ./bwr -
echo     45	 | ./gen_input | ./bwr -
echo     46	 | ./gen_input | ./bwr -
echo     47	 | ./gen_input | ./bwr -
echo     48	 | ./gen_input | ./bwr -
echo     49	 | ./gen_input | ./bwr -
echo     50	 | ./gen_input | ./bwr -
echo     51	 | ./gen_input | ./bwr -
echo     52	 | ./gen_input | ./bwr -
echo     53	 | ./gen_input | ./bwr -
echo     54	 | ./gen_input | ./bwr -
echo     55	 | ./gen_input | ./bwr -
echo     56	 | ./gen_input | ./bwr -
echo     57	 | ./gen_input | ./bwr -
echo     58	 | ./gen_input | ./bwr -
echo     59	 | ./gen_input | ./bwr -
echo     60	 | ./gen_input | ./bwr -
echo     61	 | ./gen_input | ./bwr -
echo     62	 | ./gen_input | ./bwr -
echo     63	 | ./gen_input | ./bwr -
echo     64	 | ./gen_input | ./bwr -
echo     65	 | ./gen_input | ./bwr -
echo     66	 | ./gen_input | ./bwr -
echo     67	 | ./gen_input | ./bwr -
echo     68	 | ./gen_input | ./bwr -
echo     69	 | ./gen_input | ./bwr -
echo     70	 | ./gen_input | ./bwr -
echo     71	 | ./gen_input | ./bwr -
echo     72	 | ./gen_input | ./bwr -
echo     73	 | ./gen_input | ./bwr -
echo     74	 | ./gen_input | ./bwr -
echo     75	 | ./gen_input | ./bwr -
echo     76	 | ./gen_input | ./bwr -
echo     77	 | ./gen_input | ./bwr -
echo     78	 | ./gen_input | ./bwr -
echo     79	 | ./gen_input | ./bwr -
echo     80	 | ./gen_input | ./bwr -
echo     81	 | ./gen_input | ./bwr -
echo     82	 | ./gen_input | ./bwr -
echo     83	 | ./gen_input | ./bwr -
echo     84	 | ./gen_input | ./bwr -
echo     85	 | ./gen_input | ./bwr -
echo     86	 | ./gen_input | ./bwr -
echo     87	 | ./gen_input | ./bwr -
echo     88	 | ./gen_input | ./bwr -
echo     89	 | ./gen_input | ./bwr -
echo     90	 | ./gen_input | ./bwr -
echo     91	 | ./gen_input | ./bwr -
